### ISSUE TITLE
Debugging setup of the agent!

### ISSUE THREAD

**Issue by prakharporwal** [takashi-ishio/selogger#32]
Hi @takashi-ishio 
I am trying to other feature on the project and run a project with this agent!

Do you gave a setup for debugging the project by running it and attaching a debugger ?

Is there a faster SDLC for this which you use on the project ?

Thanks

**Comment by takashi-ishio** [comment]
Thank you for your interest to the project.
I use breakpoints and single step execution on Eclipse by the following steps.
- import selogger to the workspace and build it
- import a target project to be analyzed
- Open the "Debug Configurations" dialog.
  - Create a configuration for the target project (and select a Main Class)
  - In the "Arguments" tab, add a VM argument to enable the agent, e.g. `-javaagent:${project_loc:selogger}\target\selogger-0.5.0.jar`
  - In the "Source" tab, add the selogger project to "Source Lookup Path."
- Launch the Debug configuration.

As the agent binary includes debugging information (file names and line numbers), the Source Lookup Path enables Eclipse to open corresponding files.

**Comment by prakharporwal** [comment]
Thank you for responding! @takashi-ishio  I was thinking if it is possible to have some like of hot reload feature. or class file replacement on the go. So we don't have to build the agent again and again ?

**Comment by takashi-ishio** [comment]
Thank you for the comment.  
While hot reload cannot be a part of SELogger itself, I found a workaround: You can configure the class path to enforce JVM to load a class from a directory rather than a JAR file.
In case of OpenJDK:
> -Xbootclasspath/a:${project_loc:selogger}\target\classes -javaagent:${project_loc:selogger}\target\selogger-0.5.0.jar
When you modify a source file, the updated class file will be reloaded by the debugger (if it is possible).
